<?php

/**
 * @file
 * Embed.ly support for oEmbed.module
 */

/**
 * Implementation of hook_menu().
 */
function oembedembedly_menu() {
  $items = array();

  $items['admin/build/oembed/provider/embedly'] = array(
    'title'            => 'Embed.ly',
    'description'      => 'Settings for the Embed.ly provider.',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('oembedembedly_admin'),
    'type'             => MENU_LOCAL_TASK,
    'access arguments' => array('administer oembed presets'),
  );

  return $items;
}

/**
 * Implementation of hook_default_oembedcore_provider().
 */
function oembedembedly_default_oembedcore_provider() {
  $providers = array();

  $cache = cache_get('oembedly');

  if ($cache && isset($cache->data)) {
    $json = $cache->data;
  }
  else {
    $json = drupal_http_request('http://api.embed.ly/v1/api/services');

    if ($json->code == 200) {
      $json = json_decode($json->data);
    }
    else {
      $json = FALSE;
    }

    cache_set('oembedly', $json, 'cache', time() + 3600 * ($json ? 24 : 6));

    if (variable_get('oembedembedly_default', TRUE)) {
      cache_clear_all('oembedcore:providers', 'cache');
    }
  }

  if (is_array($json)) {
    foreach ($json as $embedly_provider) {
      $provider = new stdClass;
      $provider->disabled = !variable_get('oembedembedly_default', TRUE);
      $provider->name = 'oembedembedly_' . $embedly_provider->name;
      $provider->title = $embedly_provider->displayname . ' (Embed.ly)';
      $provider->endpoint = 'http://api.embed.ly/v1/api/oembed';
      $provider->scheme = implode("\n", $embedly_provider->regex);
      $providers['oembedembedly_' . $embedly_provider->name] = $provider;
    }
  }

  return $providers;
}

function oembedembedly_admin() {
  $form['oembedembedly_default'] = array(
    '#type'          => 'radios',
    '#title'         => t('Providers enabled by default'),
    '#default_value' => variable_get('oembedembedly_default', TRUE),
    '#options'       => array(
      FALSE => t('Disabled'),
      TRUE  => t('Enabled'),
    ),
    '#description'   => t('This option defines whether providers should be enabled by default or not.'),
  );
  return system_settings_form($form);
}