<?php
// $Id$

/**
 * @file
 * Embed.ly support for oEmbed.module
 */

/**
 * Implementation of hook_menu().
 */
function oembedembedly_menu() {
  $items = array();

  $items['admin/build/oembed/provider/embedly'] = array(
    'title'            => 'Embed.ly',
    'description'      => 'Settings for the Embed.ly provider.',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('oembedembedly_admin'),
    'type'             => MENU_LOCAL_TASK,
    'access arguments' => array('administer oembed presets'),
  );

  return $items;
}

function oembedembedly_admin() {
  $form['oembedembedly_default'] = array(
    '#type'          => 'radios',
    '#title'         => t('Providers enabled by default'),
    '#default_value' => variable_get('oembedembedly_default', TRUE),
    '#options'       => array(
      FALSE => t('Disabled'),
      TRUE  => t('Enabled'),
    ),
    '#description'   => t('This option defines whether providers should be enabled by default or not.'),
  );
  return system_settings_form($form);
}

/**
 * Implement hook_ctools_plugin_api().
 */
function oembedembedly_ctools_plugin_api($module, $api) {
  if ($module == 'oembedcore' && $api == 'default_oembed_provider') {
    return array('version' => 1);
  }
}
